version: '3.1'
services:
  db:
    container_name: hae_database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=12697600000
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 99:8080

  mongodb:
    container_name: hae_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
#    command: --storageEngine wiredTiger


# mail
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

# booking
  hae_booking:
    container_name: hae_booking
    build: ./build
    ports:
      - 90:80
    volumes:
      - ./products:/app
    links:
      - db
      - mongodb
    depends_on:
      - db
      - mongodb


## we'll talk about the php container in the next step
#apache_with_php:
#  build: ./mail_build
#  volumes:
#    - ./src:/app
#  ports:
#    - "91:80"
volumes:
  mongodata: